// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fourth_term_software_labs.Data;

#nullable disable

namespace fourth_term_software_labs.Migrations.BankDb
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20260422123945_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("fourth_term_software_labs.Models.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .IsFixedLength(false);

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("RUB");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("date");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("Currency");

                    b.HasIndex("IsActive");

                    b.ToTable("BankAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = "12345678901234567890",
                            Balance = 150000.50m,
                            Currency = "RUB",
                            InterestRate = 5.5m,
                            IsActive = true,
                            OpenDate = new DateTime(2020, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerName = "Иван Петров"
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = "09876543210987654321",
                            Balance = 5000.00m,
                            Currency = "USD",
                            InterestRate = 1.2m,
                            IsActive = true,
                            OpenDate = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerName = "Мария Сидорова"
                        },
                        new
                        {
                            Id = 3,
                            AccountNumber = "11223344556677889900",
                            Balance = 5000000.00m,
                            Currency = "RUB",
                            InterestRate = 8.0m,
                            IsActive = false,
                            OpenDate = new DateTime(2018, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerName = "ООО 'Ромашка'"
                        },
                        new
                        {
                            Id = 4,
                            AccountNumber = "99887766554433221100",
                            Balance = 25000.00m,
                            Currency = "EUR",
                            InterestRate = 0.5m,
                            IsActive = true,
                            OpenDate = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerName = "Анна Иванова"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
